// See LICENSE for license details

#ifndef __SIMPLENIC_H
#define __SIMPLENIC_H

#include <cstdint>
#include <cstdio>
#include <vector>

#include "core/bridge_driver.h"
#include "core/stream_engine.h"

// TODO this should not be hardcoded here.
#define MAX_BANDWIDTH 200

struct SIMPLENICBRIDGEMODULE_struct {
#if 0
  uint64_t macaddr_upper;
  uint64_t macaddr_lower;
  uint64_t rlimit_settings;
  uint64_t pause_threshold;
  uint64_t pause_times;
  uint64_t done;
  uint64_t minobs_build_marker;
  uint64_t htnt_queue_count;
  uint64_t ntht_queue_count;
  uint64_t t_fire;
  uint64_t to_host_fire;
  uint64_t from_host_fire;
  uint64_t t_fire_blocked_to_host_valid;
  uint64_t t_fire_blocked_from_host_ready;
  uint64_t t_fire_blocked_ntht_enq_ready;
  uint64_t t_fire_blocked_htnt_deq_valid;
  uint64_t hport_to_host_valid;
  uint64_t hport_to_host_ready;
  uint64_t hport_from_host_valid;
  uint64_t hport_from_host_ready;
  uint64_t target_in_valid;
  uint64_t target_out_valid;
  uint64_t chan_to_host_valid_mask;
  uint64_t chan_to_host_ready_mask;
  uint64_t chan_to_host_fire_mask;
  uint64_t chan_to_host_blocked_mask;
  uint64_t chan_from_host_valid_mask;
  uint64_t chan_from_host_ready_mask;
  uint64_t chan_from_host_fire_mask;
  uint64_t chan_from_host_blocked_mask;
  uint64_t chan_from_host_would_valid_mask;
  uint64_t chan_from_host_would_blocked_mask;
  uint64_t from_host_leaf_valid_mask;
  uint64_t from_host_leaf_ready_mask;
  uint64_t from_host_leaf_fire_mask;
  uint64_t from_host_leaf_blocked_mask;
  uint64_t bigtoken_htnt_valid;
  uint64_t bigtoken_htnt_ready;
  uint64_t nicbig_ntht_valid;
  uint64_t nicbig_ntht_ready;
  uint64_t bigtoken_pcie_in_valid;
  uint64_t bigtoken_pcie_in_ready;
  uint64_t nicbig_pcie_out_valid;
  uint64_t nicbig_pcie_out_ready;
  uint64_t bigtoken_loop_iter;
  uint64_t bigtoken_latched_valid;
  uint64_t bigtoken_accept_count;
  uint64_t bigtoken_emit_count;
  uint64_t bigtoken_payload_emit_count;
  uint64_t bigtoken_pcie_valid_no_ready_count;
  uint64_t bigtoken_pcie_ready_no_valid_count;
  uint64_t bigtoken_htnt_valid_no_ready_count;
  uint64_t bigtoken_htnt_ready_no_valid_count;
  uint64_t bigtoken_current_slot_meta;
  uint64_t bigtoken_current_slot_data_0;
  uint64_t bigtoken_current_slot_data_1;
  uint64_t bigtoken_latched_valid_mask;
  uint64_t bigtoken_latched_ready_mask;
  uint64_t bigtoken_latched_last_mask;
  uint64_t bigtoken_last_emit_slot_mask;
  uint64_t bigtoken_ever_emit_slot_mask;
  uint64_t bigtoken_ever_payload_emit_slot_mask;
  uint64_t bigtoken_last_latched_word0_0;
  uint64_t bigtoken_last_latched_word0_1;
  uint64_t bigtoken_last_latched_word1_0;
  uint64_t bigtoken_last_latched_word1_1;
  uint64_t bigtoken_last_latched_word2_0;
  uint64_t bigtoken_last_latched_word2_1;
  uint64_t bigtoken_last_emit_data_0;
  uint64_t bigtoken_last_emit_data_1;
  uint64_t bigtoken_last_emit_meta;
  uint64_t nicbig_special_counter;
  uint64_t nicbig_full_flush_count;
  uint64_t nicbig_partial_flush_count;
  uint64_t nicbig_last_flush_slot;
  uint64_t nicbig_pcie_out_fire_count;
  uint64_t nicbig_pcie_out_enq_count;
  uint64_t nicbig_output_queue_count;
  uint64_t nicbig_ntht_fire_count;
  uint64_t nicbig_ntht_valid_no_ready_count;
  uint64_t nicbig_ntht_ready_no_valid_count;
  uint64_t nicbig_pcie_out_valid_no_ready_count;
  uint64_t nicbig_pcie_out_ready_no_valid_count;
  uint64_t nicbig_pcie_out_enq_valid_no_ready_count;
  uint64_t nicbig_flush_candidate;
  uint64_t nicbig_flush_blocked;
  uint64_t nicbig_last_ntht_data_0;
  uint64_t nicbig_last_ntht_data_1;
  uint64_t nicbig_last_ntht_meta;
  uint64_t nicbig_last_pcie_out_enq_word0_0;
  uint64_t nicbig_last_pcie_out_enq_word0_1;
  uint64_t nicbig_last_pcie_out_enq_word1_0;
  uint64_t nicbig_last_pcie_out_enq_word1_1;
  uint64_t nicbig_last_pcie_out_enq_word2_0;
  uint64_t nicbig_last_pcie_out_enq_word2_1;
  uint64_t nicbig_last_pcie_out_enq_word3_0;
  uint64_t nicbig_last_pcie_out_enq_word3_1;
  uint64_t nicbig_last_pcie_out_enq_word4_0;
  uint64_t nicbig_last_pcie_out_enq_word4_1;
  uint64_t nicbig_last_pcie_out_enq_word5_0;
  uint64_t nicbig_last_pcie_out_enq_word5_1;
  uint64_t nicbig_last_pcie_out_enq_word6_0;
  uint64_t nicbig_last_pcie_out_enq_word6_1;
  uint64_t nicbig_last_pcie_out_enq_word7_0;
  uint64_t nicbig_last_pcie_out_enq_word7_1;
  uint64_t nicbig_last_pcie_out_deq_word0_0;
  uint64_t nicbig_last_pcie_out_deq_word0_1;
  uint64_t nicbig_last_pcie_out_deq_word1_0;
  uint64_t nicbig_last_pcie_out_deq_word1_1;
  uint64_t nicbig_last_pcie_out_deq_word2_0;
  uint64_t nicbig_last_pcie_out_deq_word2_1;
  uint64_t nicbig_last_pcie_out_deq_word3_0;
  uint64_t nicbig_last_pcie_out_deq_word3_1;
  uint64_t nicbig_last_pcie_out_deq_word4_0;
  uint64_t nicbig_last_pcie_out_deq_word4_1;
  uint64_t nicbig_last_pcie_out_deq_word5_0;
  uint64_t nicbig_last_pcie_out_deq_word5_1;
  uint64_t nicbig_last_pcie_out_deq_word6_0;
  uint64_t nicbig_last_pcie_out_deq_word6_1;
  uint64_t nicbig_last_pcie_out_deq_word7_0;
  uint64_t nicbig_last_pcie_out_deq_word7_1;
  uint64_t to_host_packet_seq_0;
  uint64_t to_host_packet_seq_1;
  uint64_t to_host_packet_flit_idx;
  uint64_t t_fire_count;
  uint64_t to_host_fire_count;
  uint64_t from_host_fire_count;
  uint64_t htnt_queue_enq_fire_count;
  uint64_t htnt_queue_deq_fire_count;
  uint64_t ntht_queue_enq_fire_count;
  uint64_t ntht_queue_deq_fire_count;
  uint64_t pcie_in_fire_count;
  uint64_t pcie_out_fire_count;
  uint64_t current_blocked_reason;
  uint64_t first_blocked_valid;
  uint64_t first_blocked_reason;
  uint64_t first_blocked_queue_snapshot;
  uint64_t first_blocked_adapter_snapshot;
  uint64_t last_blocked_reason;
  uint64_t debug_cycle_0;
  uint64_t debug_cycle_1;
  uint64_t last_t_fire_cycle_0;
  uint64_t last_t_fire_cycle_1;
  uint64_t last_to_host_fire_cycle_0;
  uint64_t last_to_host_fire_cycle_1;
  uint64_t last_from_host_fire_cycle_0;
  uint64_t last_from_host_fire_cycle_1;
  uint64_t last_pcie_in_fire_cycle_0;
  uint64_t last_pcie_in_fire_cycle_1;
  uint64_t last_pcie_out_fire_cycle_0;
  uint64_t last_pcie_out_fire_cycle_1;
  uint64_t first_blocked_cycle_0;
  uint64_t first_blocked_cycle_1;
  uint64_t last_blocked_cycle_0;
  uint64_t last_blocked_cycle_1;
  uint64_t local_queues_ready;
  uint64_t target_cycle_ready;
  uint64_t to_host_ready_drive;
  uint64_t from_host_valid_drive;
  uint64_t from_host_all_ready;
  uint64_t from_host_group_fire;
  uint64_t from_host_group_blocked;
  uint64_t from_host_token_available;
  uint64_t from_host_payload_token_available;
  uint64_t from_host_empty_token_available;
  uint64_t from_host_empty_drop;
  uint64_t to_host_payload_valid;
  uint64_t to_host_empty_valid;
  uint64_t to_host_empty_bypass;
  uint64_t to_host_empty_enqueue;
  uint64_t to_host_payload_blocked;
  uint64_t htnt_queue_enq_ready;
  uint64_t htnt_queue_enq_valid;
  uint64_t htnt_queue_deq_valid;
  uint64_t htnt_queue_deq_ready;
  uint64_t ntht_queue_enq_ready;
  uint64_t ntht_queue_enq_valid;
  uint64_t ntht_queue_deq_valid;
  uint64_t ntht_queue_deq_ready;
  uint64_t target_in_bits_data_lo;
  uint64_t target_in_bits_data_hi;
  uint64_t target_in_bits_keep;
  uint64_t target_in_bits_last;
  uint64_t target_out_bits_data_lo;
  uint64_t target_out_bits_data_hi;
  uint64_t target_out_bits_keep;
  uint64_t target_out_bits_last;
  uint64_t htnt_deq_data_lo;
  uint64_t htnt_deq_data_hi;
  uint64_t htnt_deq_keep;
  uint64_t htnt_deq_last;
  uint64_t htnt_deq_data_in_valid;
  uint64_t htnt_deq_data_out_ready;
  uint64_t ntht_enq_data_lo;
  uint64_t ntht_enq_data_hi;
  uint64_t ntht_enq_keep;
  uint64_t ntht_enq_last;
  uint64_t ntht_enq_data_out_valid;
  uint64_t ntht_enq_data_in_ready;
  uint64_t from_host_current_payload_valid;
  uint64_t from_host_pending_payload_valid;
  uint64_t from_host_payload_capture;
  uint64_t from_host_payload_capture_ready;
  uint64_t from_host_payload_deq;
  uint64_t from_host_empty_drop_fire;
  uint64_t from_host_current_payload_data_lo;
  uint64_t from_host_current_payload_data_hi;
  uint64_t from_host_current_payload_keep;
  uint64_t from_host_current_payload_last;
  uint64_t from_host_pending_payload_data_lo;
  uint64_t from_host_pending_payload_data_hi;
  uint64_t from_host_pending_payload_keep;
  uint64_t from_host_pending_payload_last;
  uint64_t from_host_payload_capture_count64_0;
  uint64_t from_host_payload_capture_count64_1;
  uint64_t last_from_host_payload_capture_cycle_0;
  uint64_t last_from_host_payload_capture_cycle_1;
  uint64_t last_from_host_payload_capture_data_0;
  uint64_t last_from_host_payload_capture_data_1;
  uint64_t last_from_host_payload_capture_meta;
  uint64_t target_cycle_fire_count64_0;
  uint64_t target_cycle_fire_count64_1;
  uint64_t target_blocked_no_to_host_token_count64_0;
  uint64_t target_blocked_no_to_host_token_count64_1;
  uint64_t target_blocked_from_host_channels_count64_0;
  uint64_t target_blocked_from_host_channels_count64_1;
  uint64_t target_blocked_to_host_payload_queue_count64_0;
  uint64_t target_blocked_to_host_payload_queue_count64_1;
  uint64_t target_cycle_ready_count64_0;
  uint64_t target_cycle_ready_count64_1;
  uint64_t target_cycle_not_ready_count64_0;
  uint64_t target_cycle_not_ready_count64_1;
  uint64_t first_target_cycle_ready_valid;
  uint64_t first_target_cycle_ready_cycle_0;
  uint64_t first_target_cycle_ready_cycle_1;
  uint64_t first_target_cycle_fire_valid;
  uint64_t first_target_cycle_fire_cycle_0;
  uint64_t first_target_cycle_fire_cycle_1;
  uint64_t target_cycle_ready_streak_count64_0;
  uint64_t target_cycle_ready_streak_count64_1;
  uint64_t target_cycle_ready_max_streak_count64_0;
  uint64_t target_cycle_ready_max_streak_count64_1;
  uint64_t target_cycle_not_ready_streak_count64_0;
  uint64_t target_cycle_not_ready_streak_count64_1;
  uint64_t target_cycle_not_ready_max_streak_count64_0;
  uint64_t target_cycle_not_ready_max_streak_count64_1;
  uint64_t to_host_ready_drive_count64_0;
  uint64_t to_host_ready_drive_count64_1;
  uint64_t from_host_ready_count64_0;
  uint64_t from_host_ready_count64_1;
  uint64_t target_blocked_no_to_host_token;
  uint64_t target_blocked_no_from_host_token_count64_0;
  uint64_t target_blocked_no_from_host_token_count64_1;
  uint64_t target_blocked_from_host_channels;
  uint64_t target_blocked_to_host_payload_queue;
  uint64_t target_blocked_no_from_host_token;
  uint64_t to_host_empty_suppressed;
  uint64_t to_host_payload_fire_count64_0;
  uint64_t to_host_payload_fire_count64_1;
  uint64_t to_host_empty_fire_count64_0;
  uint64_t to_host_empty_fire_count64_1;
  uint64_t to_host_empty_enqueue_count64_0;
  uint64_t to_host_empty_enqueue_count64_1;
  uint64_t to_host_empty_suppressed_count64_0;
  uint64_t to_host_empty_suppressed_count64_1;
  uint64_t from_host_empty_drop_count64_0;
  uint64_t from_host_empty_drop_count64_1;
  uint64_t pcie_in_backpressure_count64_0;
  uint64_t pcie_in_backpressure_count64_1;
  uint64_t pcie_out_backpressure_count64_0;
  uint64_t pcie_out_backpressure_count64_1;
  uint64_t to_host_missing_valid_count64_0;
  uint64_t to_host_missing_valid_count64_1;
  uint64_t from_host_group_blocked_count64_0;
  uint64_t from_host_group_blocked_count64_1;
  uint64_t from_host_would_blocked_count64_0;
  uint64_t from_host_would_blocked_count64_1;
  uint64_t from_host_leaf_blocked_count64_0;
  uint64_t from_host_leaf_blocked_count64_1;
  uint64_t nic_in_blocked_count64_0;
  uint64_t nic_in_blocked_count64_1;
  uint64_t macaddr_blocked_count64_0;
  uint64_t macaddr_blocked_count64_1;
  uint64_t rlimit_blocked_count64_0;
  uint64_t rlimit_blocked_count64_1;
  uint64_t pauser_blocked_count64_0;
  uint64_t pauser_blocked_count64_1;
  uint64_t nic_in_fire_count64_0;
  uint64_t nic_in_fire_count64_1;
  uint64_t macaddr_fire_count64_0;
  uint64_t macaddr_fire_count64_1;
  uint64_t rlimit_fire_count64_0;
  uint64_t rlimit_fire_count64_1;
  uint64_t pauser_fire_count64_0;
  uint64_t pauser_fire_count64_1;
  uint64_t first_progress_valid;
  uint64_t first_progress_event_mask;
  uint64_t first_progress_cycle_0;
  uint64_t first_progress_cycle_1;
  uint64_t first_progress_queue_snapshot;
  uint64_t first_progress_adapter_snapshot;
  uint64_t progress_seen_mask;
  uint64_t last_progress_event_mask;
  uint64_t last_progress_cycle_0;
  uint64_t last_progress_cycle_1;
  uint64_t last_progress_queue_snapshot;
  uint64_t last_progress_adapter_snapshot;
  uint64_t blocked_streak_count64_0;
  uint64_t blocked_streak_count64_1;
  uint64_t max_blocked_streak_count64_0;
  uint64_t max_blocked_streak_count64_1;
  uint64_t from_host_leaf_blocked_streak_count64_0;
  uint64_t from_host_leaf_blocked_streak_count64_1;
  uint64_t from_host_leaf_blocked_max_streak_count64_0;
  uint64_t from_host_leaf_blocked_max_streak_count64_1;
  uint64_t to_host_payload_blocked_streak_count64_0;
  uint64_t to_host_payload_blocked_streak_count64_1;
  uint64_t to_host_payload_blocked_max_streak_count64_0;
  uint64_t to_host_payload_blocked_max_streak_count64_1;
  uint64_t to_host_ever_valid_mask;
  uint64_t to_host_ever_ready_mask;
  uint64_t to_host_ever_fire_mask;
  uint64_t to_host_ever_blocked_mask;
  uint64_t from_host_ever_valid_mask;
  uint64_t from_host_ever_ready_mask;
  uint64_t from_host_ever_fire_mask;
  uint64_t from_host_ever_blocked_mask;
  uint64_t last_blocked_to_host_valid_mask;
  uint64_t last_blocked_to_host_ready_mask;
  uint64_t last_blocked_to_host_fire_mask;
  uint64_t last_blocked_to_host_blocked_mask;
  uint64_t last_blocked_from_host_valid_mask;
  uint64_t last_blocked_from_host_ready_mask;
  uint64_t last_blocked_from_host_fire_mask;
  uint64_t last_blocked_from_host_blocked_mask;
  uint64_t last_blocked_queue_snapshot;
  uint64_t last_blocked_adapter_snapshot;
  uint64_t first_from_host_blocked_valid;
  uint64_t first_from_host_blocked_cycle_0;
  uint64_t first_from_host_blocked_cycle_1;
  uint64_t first_from_host_blocked_ready_mask;
  uint64_t first_from_host_blocked_valid_mask;
  uint64_t last_from_host_blocked_cycle_0;
  uint64_t last_from_host_blocked_cycle_1;
  uint64_t last_from_host_blocked_ready_mask;
  uint64_t last_from_host_blocked_valid_mask;
  uint64_t first_to_host_blocked_valid;
  uint64_t first_to_host_blocked_cycle_0;
  uint64_t first_to_host_blocked_cycle_1;
  uint64_t first_to_host_blocked_ready_mask;
  uint64_t first_to_host_blocked_valid_mask;
  uint64_t last_to_host_blocked_cycle_0;
  uint64_t last_to_host_blocked_cycle_1;
  uint64_t last_to_host_blocked_ready_mask;
  uint64_t last_to_host_blocked_valid_mask;
  uint64_t first_from_host_leaf_blocked_valid;
  uint64_t first_from_host_leaf_blocked_cycle_0;
  uint64_t first_from_host_leaf_blocked_cycle_1;
  uint64_t first_from_host_leaf_blocked_mask;
  uint64_t last_from_host_leaf_blocked_cycle_0;
  uint64_t last_from_host_leaf_blocked_cycle_1;
  uint64_t last_from_host_leaf_blocked_mask;
  uint64_t htnt_payload_enq_count64_0;
  uint64_t htnt_payload_enq_count64_1;
  uint64_t htnt_empty_enq_count64_0;
  uint64_t htnt_empty_enq_count64_1;
  uint64_t target_in_payload_fire_count64_0;
  uint64_t target_in_payload_fire_count64_1;
  uint64_t target_in_empty_fire_count64_0;
  uint64_t target_in_empty_fire_count64_1;
  uint64_t ntht_payload_enq_count64_0;
  uint64_t ntht_payload_enq_count64_1;
  uint64_t ntht_payload_deq_count64_0;
  uint64_t ntht_payload_deq_count64_1;
  uint64_t last_htnt_enq_cycle_0;
  uint64_t last_htnt_enq_cycle_1;
  uint64_t last_htnt_enq_data_0;
  uint64_t last_htnt_enq_data_1;
  uint64_t last_htnt_enq_meta;
  uint64_t last_htnt_deq_cycle_0;
  uint64_t last_htnt_deq_cycle_1;
  uint64_t last_htnt_deq_data_0;
  uint64_t last_htnt_deq_data_1;
  uint64_t last_htnt_deq_meta;
  uint64_t last_target_in_fire_cycle_0;
  uint64_t last_target_in_fire_cycle_1;
  uint64_t last_target_in_fire_data_0;
  uint64_t last_target_in_fire_data_1;
  uint64_t last_target_in_fire_meta;
  uint64_t last_target_out_fire_cycle_0;
  uint64_t last_target_out_fire_cycle_1;
  uint64_t last_target_out_fire_data_0;
  uint64_t last_target_out_fire_data_1;
  uint64_t last_target_out_fire_meta;
  uint64_t last_ntht_enq_cycle_0;
  uint64_t last_ntht_enq_cycle_1;
  uint64_t last_ntht_enq_data_0;
  uint64_t last_ntht_enq_data_1;
  uint64_t last_ntht_enq_meta;
  uint64_t last_ntht_deq_cycle_0;
  uint64_t last_ntht_deq_cycle_1;
  uint64_t last_ntht_deq_data_0;
  uint64_t last_ntht_deq_data_1;
  uint64_t last_ntht_deq_meta;
  uint64_t first_htnt_payload_enq_cycle_0;
  uint64_t first_htnt_payload_enq_cycle_1;
  uint64_t first_target_in_payload_fire_cycle_0;
  uint64_t first_target_in_payload_fire_cycle_1;
  uint64_t first_target_out_payload_fire_cycle_0;
  uint64_t first_target_out_payload_fire_cycle_1;
  uint64_t first_ntht_payload_enq_cycle_0;
  uint64_t first_ntht_payload_enq_cycle_1;
  uint64_t first_pcie_out_fire_cycle_0;
  uint64_t first_pcie_out_fire_cycle_1;
#endif
  uint64_t macaddr_upper;
  uint64_t macaddr_lower;
  uint64_t rlimit_settings;
  uint64_t pause_threshold;
  uint64_t pause_times;
  uint64_t done;
  uint64_t minobs_build_marker;
  uint64_t htnt_queue_count;
  uint64_t ntht_queue_count;
  uint64_t t_fire;
  uint64_t to_host_fire;
  uint64_t from_host_fire;
  uint64_t hport_to_host_valid;
  uint64_t hport_to_host_ready;
  uint64_t hport_from_host_valid;
  uint64_t hport_from_host_ready;
  uint64_t target_in_valid;
  uint64_t target_out_valid;
  uint64_t target_cycle_ready;
  uint64_t to_host_ready_drive;
  uint64_t from_host_all_ready;
  uint64_t from_host_token_available;
  uint64_t from_host_payload_token_available;
  uint64_t from_host_empty_token_available;
  uint64_t from_host_empty_drop;
  uint64_t from_host_current_payload_valid;
  uint64_t from_host_pending_payload_valid;
  uint64_t from_host_payload_capture;
  uint64_t from_host_payload_capture_ready;
  uint64_t from_host_payload_deq;
  uint64_t from_host_empty_drop_fire;
  uint64_t to_host_payload_valid;
  uint64_t to_host_empty_valid;
  uint64_t to_host_empty_suppressed;
  uint64_t to_host_payload_blocked;
  uint64_t htnt_queue_enq_valid;
  uint64_t htnt_queue_enq_ready;
  uint64_t htnt_queue_deq_valid;
  uint64_t htnt_queue_deq_ready;
  uint64_t ntht_queue_enq_valid;
  uint64_t ntht_queue_enq_ready;
  uint64_t ntht_queue_deq_valid;
  uint64_t ntht_queue_deq_ready;
  uint64_t bigtoken_pcie_in_valid;
  uint64_t bigtoken_pcie_in_ready;
  uint64_t nicbig_pcie_out_valid;
  uint64_t nicbig_pcie_out_ready;
  uint64_t nicbig_output_queue_count;
  uint64_t current_blocked_reason;
  uint64_t target_blocked_no_to_host_token;
  uint64_t target_blocked_from_host_channels;
  uint64_t target_blocked_to_host_payload_queue;
  uint64_t debug_cycle_0;
  uint64_t debug_cycle_1;
  uint64_t target_cycle_fire_count64_0;
  uint64_t target_cycle_fire_count64_1;
  uint64_t target_cycle_ready_count64_0;
  uint64_t target_cycle_ready_count64_1;
  uint64_t target_cycle_not_ready_count64_0;
  uint64_t target_cycle_not_ready_count64_1;
  uint64_t from_host_payload_capture_count64_0;
  uint64_t from_host_payload_capture_count64_1;
  uint64_t from_host_empty_drop_count64_0;
  uint64_t from_host_empty_drop_count64_1;
  uint64_t to_host_payload_fire_count64_0;
  uint64_t to_host_payload_fire_count64_1;
  uint64_t to_host_empty_fire_count64_0;
  uint64_t to_host_empty_fire_count64_1;
  uint64_t pcie_in_fire_count;
  uint64_t pcie_out_fire_count;
};

class simplenic_t final : public streaming_bridge_driver_t {
public:
  /// The identifier for the bridge type used for casts.
  static char KIND;

  simplenic_t(simif_t &sim,
              StreamEngine &stream,
              const SIMPLENICBRIDGEMODULE_struct &addrs,
              int simplenicno,
              const std::vector<std::string> &args,
              int stream_to_cpu_idx,
              int stream_to_cpu_depth,
              int stream_from_cpu_idx,
              int stream_from_cpu_depth);
  ~simplenic_t() override;

  void init() override;
  void tick() override;
  void finish() override {}

private:
  const SIMPLENICBRIDGEMODULE_struct mmio_addrs;
  uint64_t mac_lendian;
  char *pcis_read_bufs[2];
  char *pcis_write_bufs[2];
  int rlimit_inc, rlimit_period, rlimit_size;
  int pause_threshold, pause_quanta, pause_refresh;

  // link latency in cycles
  // assuming 3.2 GHz, this number / 3.2 = link latency in ns
  // e.g. setting this to 6405 gives you 6405/3.2 = 2001.5625 ns latency
  // IMPORTANT: this must be a multiple of 7
  int LINKLATENCY;
  FILE *niclog;
  bool loopback;

  // checking for token loss
  int currentround = 0;
  uint64_t successful_rounds = 0;
  uint32_t round_debug_limit = 0;
  bool relaxed_required_bytes = false;
  uint32_t empty_switch_poll_interval = 1;
  bool round_pending = false;
  bool pending_peer_snapshot_valid = false;
  uint32_t pending_token_bytes = 0;
  uint32_t pending_push_offset_bytes = 0;
  uint32_t pending_peer_valid_flits = 0;
  bool pending_round_from_empty_pull = false;
  bool pcis_read_buf_dirty[2] = {true, true};
  uint64_t pulled_rounds_started = 0;
  uint64_t partial_pull_rounds_started = 0;
  uint64_t empty_rounds_started = 0;
  uint64_t empty_rounds_skipped_switch = 0;
  uint64_t peer_input_rounds = 0;
  uint64_t peer_empty_rounds = 0;
  uint32_t last_peer_valid_flits = 0;
  uint64_t last_peer_input_round = 0;
  uint64_t peer_wait_ticks = 0;
  uint64_t push_blocked_ticks = 0;
  uint64_t pull_empty_ticks = 0;
  uint32_t token_debug_limit = 0;
  uint64_t to_host_token_debug_events = 0;
  uint64_t peer_token_debug_events = 0;
  uint64_t push_token_debug_events = 0;
  char *pending_peer_buf = nullptr;

  // only for TOKENVERIFY
  const int stream_to_cpu_idx;
  const int stream_from_cpu_idx;

  void dump_host_debug(const char *context,
                       uint32_t requested_bytes,
                       uint32_t actual_bytes);
  void dump_tx_path_snapshot(const char *context);
  void dump_token_buffer(const char *context,
                         const char *buf,
                         uint32_t bigtokens,
                         uint32_t actual_bytes,
                         uint64_t *event_counter);
};

#endif // __SIMPLENIC_H
